### ISSUE TITLE
Output files

### ISSUE THREAD

**Issue by isabelladistefano** [CSU-KangHu/HiTE#1]
Hello,

I've just tried HiTE, only on one chromosome for now, and trying to run it on assemblies now.

I would like a bit more information on the output files:

I understand that the output: 
confident_TE.cons.fa.classified
is the most final/complete output of TEs found?

However it doesn't give the coordinates on the genome like the confident_TE.cons.fa.domain does.

I would like the coordinates of the TEs on the genome. 

Best wishes,

Isabella

**Comment by CSU-KangHu** [comment]
Hello Isabella,

Thank you for using HiTE. We hope it brings you novel discoveries and insights.

> I understand that the output:
confident_TE.cons.fa.classified
is the most final/complete output of TEs found?

Yes, the final outcome of HiTE is the generation of a clean TE library, namely **confident_TE.cons.fa.classified**.

> However it doesn't give the coordinates on the genome like the confident_TE.cons.fa.domain does.

The **confident_TE.cons.fa.domain** file contains the coordinates information of domains within TEs. Obtaining the coordinates of TEs on the genome is a straightforward process that can be achieved using any suitable approach from the following options:
1. HiTE installed via conda.
- `conda activate HiTE`

2. HiTE installed via Singularity.
- `singularity shell -B ${path}:${path} ${HiTE.sif}`  # Enter the container. e.g., `singularity shell -B /home/hukang:/home/hukang /home/hukang/HiTE.sif`

3. Run RepeatMasker.
- `cd ${HiTE_out_dir} && RepeatMasker -e ncbi -pa 40 -q -no_is -norna -nolow -div 40 -gff -lib confident_TE.cons.fa.classified -cutoff 225 ${your_genome_path} && mv ${your_genome_path}.out ${HiTE_out_dir}/HiTE.out && mv ${your_genome_path}.tbl ${HiTE_out_dir}/HiTE.tbl && mv ${your_genome_path}.out.gff ${HiTE_out_dir}/HiTE.gff`

**Or**

4. Update the latest code for HiTE. 

- I have integrated the aforementioned process into the HiTE pipeline for convenience. You can obtain the latest code, including Conda, Docker, and Singularity. Then run HiTE with additional parameter `--annotate 1`.

Three files, **HiTE.out**, **HiTE.gff**, and **HiTE.tbl**, will be generated. The **HiTE.out** and **HiTE.gff**, function as genome annotation files, with **HiTE.gff** being visualizable in the IGV (Integrative Genomics Viewer). Additionally, **HiTE.tbl** offers statistical information  on the proportion of each transposon type within the genome.

Best wishes,

Kang

**Comment by isabelladistefano** [comment]
Hi Kang,

Thank you for your response. I deleted my HiTE files,path and conda environments and re-installed HiTE with conda however I get the error:

main.py: error: unrecognized arguments: --annotate 1

Still. Do I need to do something else to get the newest code?

Best,

Isabella

**Comment by CSU-KangHu** [comment]
Hi Isabella,

> main.py: error: unrecognized arguments: --annotate 1

This error is likely due to the code not being updated to the latest version. I just retested it, and the program runs smoothly. You may need to redownload the code.

![1688782139761](https://github.com/CSU-KangHu/HiTE/assets/22925278/9f0b3f0e-d802-467a-99a1-f8872ca788f2)

![1688782110524](https://github.com/CSU-KangHu/HiTE/assets/22925278/f68e39dc-18b0-4bce-8e7a-fa2bc6749860)

By the way, since I haven't made any modifications to the conda environment, you don't need to delete the existing HiTE conda environment. You just need to redownload the code, activate the environment with `conda activate HiTE`, and HiTE should run smoothly with the parameter `--annotate 1`.

**Comment by isabelladistefano** [comment]
Hello Kang,

My HPC is down at the moment but when it's back up and running, i'll give it another try.

Thank you very much for all your help : ) 

Isabella

**Comment by CSU-KangHu** [comment]
Hi Isabella,

To install HiTE via Conda, you need to update the Dfam library. The simplest way to update the Dfam library can be found [here](https://github.com/CSU-KangHu/HiTE#classified). Since you are using an HPC platform, I suggest trying the Singularity installation mode. The image includes all the dependencies, so no additional installations are required.

Kang
